### ISSUE TITLE
Validate user signup information client-side & server-side

### ISSUE THREAD

**Issue by dosaki** [msc-dtss/super6assignment#40]
See `/users/signup` route on [`routes/users.js`](https://github.com/msc-dtss/super6assignment/blob/master/routes/users.js)

**Comment by neilmusgrove** [comment]
@dosaki could you add a little more detail on what you mean here, we were a bit unsure. Is it form validation of email etc?

**Comment by dosaki** [comment]
Yes, some form validation.
Ensuring the email looks like an email.

This should also include reporting any errors that come from server-side validation

**Comment by MikeKeightley** [comment]
I've added some basic password validation client side now, so we're looking for 7 more characters, with atleast one upper and one lowercase letter - I think this gives some consideration for security, although if we decide its not enough, it's really easy to change.

Email is already validating as part of the input-type: email, so not sure we need to add any more to that?

I've also added some tool tips to show this info to the players.  I'll have a look at handling server side errors tomorrow.

**Comment by neilmusgrove** [comment]
Sounds great 👍🏻

**Comment by MikeKeightley** [comment]
Hmm, I've no w pulled the latest code, and updated userForm.ejs with my password validation, and doesn't work! I'm using exactly the same code, and the form itself doesn't appear to have changed.  Any Ideas @neilmusgrove @dosaki ? The below worked beautifully yesterday.

<img width="910" alt="Screenshot 2019-11-17 at 13 49 20" src="https://user-images.githubusercontent.com/55582938/69008330-1fd81300-0941-11ea-963f-5ce0095f4f89.png">

**Comment by dosaki** [comment]
Push to your branch and I'll pull it to have a look

**Comment by MikeKeightley** [comment]
Cheers - should be a branch available now with it on....I'm sure its something trivial as usual!

**Comment by MikeKeightley** [comment]
@dosaki @neilmusgrove i've just been having a quick look at this, and tried using 'express-validator' as part of the users route, and I've written it based on the docs here: https://express-validator.github.io/docs/ 

it looks like it should return some json if the validation is not met, but it's confusing me because I already have validation on the registration form itself, so you can't actually generate the request the request to pass through the server side validation steps, if that makes any sense at all? Should i be validating on the server side for the same criteria as on the sign up form, or have I got the wrong end of the stick.

If not, my next plan would be to look at doing something similar to what we do with validating bets, although I am conscious we are getting short of time now.

I've also attached what i've written - It does still let you successfully register a user with this code present, it just doesn't return any validation errors.  I've also got require(express-validator) at the top of the users route, but couldn't include in screen shot below.

![image](https://user-images.githubusercontent.com/55582938/69534182-2c77ef00-0f71-11ea-8a55-c0fde3cb7353.png)

**Comment by dosaki** [comment]
The code in the docs has the creation of the user inside the callback while you have it outside.

Also, on the outside you also have a `res.redirect` which will change the `res` object.

Because you do that return on the callback function, that doesn't return from the main route function, which means it will still run the rest of the code.

Did that make sense?

**Comment by MikeKeightley** [comment]
Yeah, I think it does, but I'm not 100% certain on how to fix....!  Is it just a case of moving it back inside the callback?  If so, do I need to move the whole block right down to the redirect? Or do i need to do something different with the res.redirect because we already have the res object?  Happy to discuss tonight if it's easier (normally understand things better when shown haha!)?

**Comment by dosaki** [comment]
You need to make sure that if you find any error, you exit out of that router function before you try to create the user and before you do any redirects.

**Comment by MikeKeightley** [comment]
Thanks, that makes sense! Will try this afternoon.
