### ISSUE TITLE
Data Structure Design

### ISSUE THREAD

**Issue by MikeKeightley** [msc-dtss/super6assignment#7]
I've started designing some ideas for the database, initially looking at users, and how we may want to structure the way rounds/games and bets interact.  I've attached a very basic diagram with a few annotations - i know we dont have to delcare datatypes as such, but it might be worth keeping a record of what we expect in each field incase it affects how we write the code for each module.  I've tested some idea's in Mongo already, but I've come up with a few questions/clarifications:

- How do we want to store the users bet results/points?  Do we keep this in the standard user table, against their record, or in a separate collection (possible in the 'rounds' collection, so it can be referenced against the round, and a total calculated from there?)

- How do we structure the 'tournaments' collection?  Would we use this as a way of displaying the round results and overall total in a league format?

- I've started out by not having a 'teams' collection, as i was listing all matches and teams in the 'games' collection.  Would this be sufficient, or would it be worth separating the teams out and referencing them in the other collections by their id?

![Super6 Collection Structure](https://user-images.githubusercontent.com/55582938/66078615-3fb2a380-e55a-11e9-82e7-264608c152ff.jpg)

**Comment by neilmusgrove** [comment]
Looks good! On your queries, here's my thoughts:

I think a results/points table would be useful (user results, not rugby match results), with FK's of user and round (or you could FK on bet since that is limited to 1 user per round). The details in a user table would ideally only be details specifically about a person. 

For teams I would stick with string values personally because we don't need to compile or calculate anything to do with the teams and we don't need any metadata on them(they could in-fact be different teams each round or random names and it wouldn't matter for our game). Sticking to string values keeps it nice and simple. I just had a thought though about adding flags/shirts in the ui which would be nice but this could simply be done using the team name matching an image file.

**Comment by MikeKeightley** [comment]
Thanks @neilmusgrove - I've just about got a basic database complete now on my local machine.  Just a results and League table collection to go now.  Is there a way to get this onto GitHub through VS Code so you guys can pull it down, or would I need to share the files like Martin did during the lectures?

**Comment by neilmusgrove** [comment]
You can export and import from/to Mongo with the commands here - https://docs.mongodb.com/manual/reference/program/mongoexport/.

If you have a json export file you can easily add that to the repos to share and it can be tweaked with version control as well.

**Comment by dosaki** [comment]
Do we need a collection for all the Teams? Or am I thinking too "relationally"?

**Comment by MikeKeightley** [comment]
@dosaki I did have one in my very early design, but as Neil says, not sure we need to do any complex logic/calculations around the individual teams, and if we do need to refer to them, just refer to the team string name in the games collection?  I'm playing with 'results' and a 'league' table at the moment.  I'll have something uploaded tomorrow night for you all to see/play with.

**Comment by dosaki** [comment]
Lets keep evolving this via code & pull requests then!
